[tool.poetry]
name = "daa"
version = "0.1.0"
description = "A Design and Analysis of Algorithms library"
authors = ["Pablo <pablohuggem@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/Tomcat-42/daa"
repository = "https://github.com/Tomcat-42/daa"
keywords = ["daa", "algorithms", "data structures", "sorting", "searching", "c++", "c++11", "c++ module"]
packages = [{include ="daa", format = "wheel"}]
exclude = ["daa/compile.py"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.scripts]
compile = "daa.compile:main"


[build-system]
requires = ["poetry-core", "setuptools", "wheel", "pybind11"]
build-backend = "setuptools.build_meta"
