[tool.poetry]
name = "daa"
version = "0.0.5"
description = "A Design and Analysis of Algorithms library"
authors = ["Pablo <pablohuggem@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/Tomcat-42/daa"
repository = "https://github.com/Tomcat-42/daa"
keywords = ["daa", "algorithms", "data structures", "sorting", "searching", "c++", "c++11", "c++ module"]
packages = [
  { include = "libdaa.so", from = "./daa/" }
]
# include = ["./daa/libdaa.so"]
# exclude = ["./libdaa"]
build = "build.py"

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["setuptools", "wheel", "cmake>=3.12"]
build-backend = "setuptools.build_meta"
